### ISSUE TITLE
 files are missing

### ISSUE THREAD

**Issue by Jzetera** [navchetan-awasthi/dnnpat#1]
I want to replicate your work Deep Neural-Network Based Sinogram Super-resolution and Bandwidth Enhancement for Limited Data Photoacoustic Tomography however when running the matlab file from test_data_generation.m it should load a bv_sinogram1.mat file that is not found in the github, it could advise me ?

**Comment by navchetan-awasthi** [comment]
The testing files have not been provided as some of these are the dataset acquired experimentally . We just provided the framework if anyone wants to use it for their dataset. If you want to create the data bv_sinogram1.mat, you need to run the forward simulation using k-wave and can get the sinogram data to be used further in the analysis.

**Comment by Jzetera** [comment]
Would it be possible to share those files with me or could you tell me which simulation of k-wave would be adequate to generate this data?

**Comment by navchetan-awasthi** [comment]
Sorry for the late reply. Please give me time by the end of this week. If I can't share it, I can help you in generation of the data.

**Comment by Jzetera** [comment]
I thank you, I share my email for contact zetera0702@gmail.com

**Comment by Jzetera** [comment]
hi, sorry if you were able to get the test_samples folder?

**Comment by navchetan-awasthi** [comment]
I cannot find the testing files but it can be easily generated using the k-wave toolbox.
You can make use of this repository for making the data again.
https://github.com/navchetan-awasthi/Vector-Extrapolation-Photoacoustic

**Comment by Jzetera** [comment]
![image](https://user-images.githubusercontent.com/92754194/141858657-a651cc18-b3b9-4815-8ba5-be51647502ec.png)
In the file to generate the data it mentions an image, what type of image does it refer to?

**Comment by Jzetera** [comment]
excuse me, the raw data is are available in this link? https://drive.google.com/drive/u/0/folders/1GoaDXnXWBry_31XEfzxRnXpk2eeVMlhT

**Comment by navchetan-awasthi** [comment]
yes, the raw data is available here.

**Comment by Jzetera** [comment]
Hi, sorry I'm trying to train the SRCNN network, the training is completed but in the end it throws me the following error, what do you mean by add reflective padding? I hope you can guide me, thank you
![image](https://user-images.githubusercontent.com/92754194/143691901-e27f0eb4-4201-4daa-ac34-30283a30cce3.png)

**Comment by Jzetera** [comment]
the content of my TEST_PATH is as follows
![image](https://user-images.githubusercontent.com/92754194/143691961-76d303c1-102e-4ba4-8236-a096d42cb323.png)

**Comment by Jzetera** [comment]
hello, I am waiting for an answer I am stuck at that point since it shows me the error mentioned above when doing the training

**Comment by navchetan-awasthi** [comment]
It might be because of the version of the software  used. I don't think I can do much in that. Please try to search for this error.
